name: "GIT GUARDIAN 🔒"

on:
  push:
  pull_request:

jobs:
  GIT_GUARDIAN:
    name: "GIT GUARDIAN 🔒"
    runs-on: ubuntu-latest
    steps:
      - name: "CHECKOUT ⤵️"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "SCAN 🔍"
        uses: GitGuardian/ggshield-action@v1.22.0
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}