name: "PURGE 🫧"

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  CLEAR_CACHE:
    name: "CLEAR CACHE 🧹"
    runs-on: ubuntu-latest
    steps:
      - uses: MyAlbum/purge-cache@v2
        with:
          accessed: true
          max-age: 86400